version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tracking_db}
      POSTGRES_USER: ${POSTGRES_USER:-tracking_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tracking_secure_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-tracking_user} -d ${POSTGRES_DB:-tracking_db}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - tracking_network

  web:
    build: .
    restart: always
    environment:
      - DEBUG=False
      - POSTGRES_DB=${POSTGRES_DB:-tracking_db}
      - POSTGRES_USER=${POSTGRES_USER:-tracking_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-tracking_secure_password}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-this-in-production}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - ALLOWED_HOSTS=api.gunswithroses.com,localhost,127.0.0.1
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tracking_network
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 2G
        reservations:
          cpus: '0.4'
          memory: 1G

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro
    depends_on:
      - web
    networks:
      - tracking_network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 512M

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  tracking_network:
    driver: bridge
